<?php

/**
* Implements hook_theme()
*/

function etna_ajax_block_theme($existing, $type, $theme, $path) {
return [
'ajax_view_demo' => [],
];
}


/**
 * Implements hook_views_pre_render().
 */
function etna_ajax_block_views_pre_render($view)
{

}

/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter().
 */
function etna_ajax_block_block_view_news_view_block_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block)
{


}